import type { MemberPermissions, MemberActions } from './organization'

export type RolePreset = 'admin' | 'manager' | 'seller' | 'viewer' | 'cliente'

export const ROLE_PRESETS: Record<RolePreset, MemberPermissions> = {
  admin: {
    pages: ['/contatos', '/funil', '/funil/produtividade', '/conversao', '/cadencia', '/ligacoes', '/ligacoes/configuracao', '/ligacoes/disparo', '/ligacoes/historico', '/analytics', '/projecao-vendas', '/automacoes', '/campanhas', '/admin/usuarios', '/admin/email', '/admin/funis', '/admin/icp', '/admin/centros-custo', '/admin/propostas', '/admin/creditos', '/admin/estrategia', '/admin/plano'],
    actions: {
      canCreateContacts: true,
      canEditContacts: true,
      canDeleteContacts: true,
      canCreateProposals: true,
      canExportData: true,
      canManageFunnels: true,
      canManageUsers: true,
      canTriggerCalls: true,
      canViewReports: true,
      canManageSettings: true,
      canTransferLeads: true,
    },
    viewScope: 'all',
  },
  manager: {
    pages: ['/contatos', '/funil', '/funil/produtividade', '/conversao', '/cadencia', '/ligacoes'],
    actions: {
      canCreateContacts: true,
      canEditContacts: true,
      canDeleteContacts: true,
      canCreateProposals: true,
      canExportData: true,
      canManageFunnels: true,
      canManageUsers: false,
      canTriggerCalls: true,
      canViewReports: true,
      canManageSettings: false,
      canTransferLeads: true,
    },
    viewScope: 'all',
  },
  seller: {
    pages: ['/contatos', '/funil', '/conversao'],
    actions: {
      canCreateContacts: true,
      canEditContacts: true,
      canDeleteContacts: false,
      canCreateProposals: true,
      canExportData: false,
      canManageFunnels: false,
      canManageUsers: false,
      canTriggerCalls: false,
      canViewReports: false,
      canManageSettings: false,
      canTransferLeads: true,
    },
    viewScope: 'own',
  },
  viewer: {
    pages: ['/contatos', '/funil'],
    actions: {
      canCreateContacts: false,
      canEditContacts: false,
      canDeleteContacts: false,
      canCreateProposals: false,
      canExportData: false,
      canManageFunnels: false,
      canManageUsers: false,
      canTriggerCalls: false,
      canViewReports: false,
      canManageSettings: false,
      canTransferLeads: false,
    },
    viewScope: 'all',
  },
  cliente: {
    pages: ['/contatos', '/funil'],
    actions: {
      canCreateContacts: false,
      canEditContacts: false,
      canDeleteContacts: false,
      canCreateProposals: false,
      canExportData: false,
      canManageFunnels: false,
      canManageUsers: false,
      canTriggerCalls: false,
      canViewReports: false,
      canManageSettings: false,
      canTransferLeads: false,
    },
    viewScope: 'own',
  },
}

export const ALL_PAGES = [
  { path: '/contatos', label: 'Gestao de Contatos', feature: 'contacts' },
  { path: '/funil', label: 'Funil de Vendas', feature: 'funnel' },
  { path: '/funil/produtividade', label: 'Produtividade', feature: 'productivity' },
  { path: '/conversao', label: 'Conversao do Funil', feature: 'funnel' },
  { path: '/cadencia', label: 'Cadencia', feature: 'cadence' },
  { path: '/ligacoes', label: 'Agente de Ligacao', feature: 'voice_agent' },
  { path: '/ligacoes/configuracao', label: 'Config. do Agente', feature: 'voice_agent' },
  { path: '/ligacoes/disparo', label: 'Disparo Massivo', feature: 'voice_agent' },
  { path: '/ligacoes/historico', label: 'Historico de Ligacoes', feature: 'voice_agent' },
  { path: '/analytics', label: 'Analises & Insights', feature: 'analytics' },
  { path: '/projecao-vendas', label: 'Projecao de Vendas', feature: 'funnel' },
  { path: '/automacoes', label: 'Automacoes IA', feature: 'automation' },
  { path: '/campanhas', label: 'Campanhas', feature: 'campaigns' },
  { path: '/admin/usuarios', label: 'Gerenciar Usuarios', feature: 'contacts' },
  { path: '/admin/email', label: 'Email', feature: 'contacts' },
  { path: '/admin/funis', label: 'Acesso a Funis', feature: 'funnel' },
  { path: '/admin/icp', label: 'Perfis ICP', feature: 'contacts' },
  { path: '/admin/centros-custo', label: 'Centros de Custo', feature: 'contacts' },
  { path: '/admin/propostas', label: 'Config. Propostas', feature: 'contacts' },
  { path: '/admin/creditos', label: 'Creditos', feature: 'voice_agent' },
  { path: '/admin/estrategia', label: 'Estrategia Comercial', feature: 'contacts' },
  { path: '/admin/plano', label: 'Meu Plano', feature: 'contacts' },
] as const

export const ALL_ACTIONS: { key: keyof MemberActions; label: string }[] = [
  { key: 'canCreateContacts', label: 'Criar contatos' },
  { key: 'canEditContacts', label: 'Editar contatos' },
  { key: 'canDeleteContacts', label: 'Excluir contatos' },
  { key: 'canCreateProposals', label: 'Criar propostas' },
  { key: 'canExportData', label: 'Exportar dados' },
  { key: 'canManageFunnels', label: 'Gerenciar funis' },
  { key: 'canManageUsers', label: 'Gerenciar usuarios' },
  { key: 'canTriggerCalls', label: 'Disparar ligacoes' },
  { key: 'canViewReports', label: 'Ver relatorios' },
  { key: 'canManageSettings', label: 'Gerenciar configuracoes' },
  { key: 'canTransferLeads', label: 'Transferir leads' },
]
